# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgo" do
  name "rgo"
  desc "rgo is a CLI to release a Homebrew-tap recipe, Scoop App Manifest, and a winget manifest built with GoReleaser."
  homepage "https://github.com/suzuki-shunsuke/rgo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rgo"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/rgo/releases/download/v#{version}/rgo_darwin_amd64.tar.gz"
      sha256 "43b9bd1ae1f328a8f0b70290567facae1bb112bcb605ffa9730ed9b56b23892f"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/rgo/releases/download/v#{version}/rgo_darwin_arm64.tar.gz"
      sha256 "aafe3630d69c77ab509e36f9d382954f4b59ce308fd4985d2012cd9113239ac1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/rgo/releases/download/v#{version}/rgo_linux_amd64.tar.gz"
      sha256 "93ab7855a7b3c0ce1af7422f823bc0c3d1b8f8022cced0894ac34a64d7528b2a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/rgo/releases/download/v#{version}/rgo_linux_arm64.tar.gz"
      sha256 "17cb4ac33657ab8336ecc9877a70040744ba541035c6ae45ebdb3331aab536b0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rgo"]
    end
  end

  # No zap stanza required
end
